package com.glob.ufriends.apis;

import com.glob.ufriends.entities.ForumTopic;
import com.glob.ufriends.services.ForumTopicService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import org.springframework.transaction.annotation.Transactional;

@RequestMapping(value = "/api/v1/forumTopic")
@RestController
public class ForumTopicController {

    @Autowired
    private ForumTopicService service;

    /*
    * JSON Object for Forum Topic:
    *
    * {
    *   id: int, // Not needed in post. This is autogenerated via a sequence in the db
    *   authorId: {id: String}, // User object that has the id of the user
    *   title: String,
    *   description: String,
    *   creationDate: Date || null, // Not needed in post. The date is set in the DB using a trigger
    *   commentsQuantity: int, // Set it to 0 in the post for known reasons
    *   isAnon: int (boolean) // 0 for false, 1 for true
    * }
    *
    * */
    @PostMapping
    public ForumTopic addForumTopic(@RequestBody ForumTopic forumTopic) {
        return service.saveForumTopic(forumTopic);
    }

    @GetMapping
    public List<ForumTopic> findAllForumTopics() {
        return service.getAllForumTopics();
    }

    @GetMapping(path = "{id}")
    public ForumTopic findForumTopicById(@PathVariable("id") int id) {
        return service.getForumTopic(id);
    }

    @GetMapping(path = "/orderByDateDesc")
    public List<ForumTopic> findAllForumsByDateDesc() {
        return service.getForumTopicsOrderedByCDate();
    }
    
    @Transactional
    @DeleteMapping
    public void deleteForumTopic(@RequestBody ForumTopic forumTopic){
        service.deleteForumTopic(forumTopic);
    }
    
}
